<?xml version="1.0" encoding="UTF-8"?>
<testng-results ignored="0" total="2" passed="0" failed="2" skipped="0">
  <reporter-output>
    <line>
      <![CDATA[All test Execution started]]>
    </line>
    <line>
      <![CDATA[Starting test is test_1]]>
    </line>
    <line>
      <![CDATA[Test failed test_1]]>
    </line>
    <line>
      <![CDATA[Starting test is test_1]]>
    </line>
    <line>
      <![CDATA[Test failed test_1]]>
    </line>
  </reporter-output>
  <suite started-at="2020-09-25T15:19:57 CEST" name="Default suite" finished-at="2020-09-25T15:20:16 CEST" duration-ms="18452">
    <groups>
    </groups>
    <test started-at="2020-09-25T15:19:57 CEST" name="Default test" finished-at="2020-09-25T15:20:16 CEST" duration-ms="18452">
      <class name="de.alain.TestNGParallel.TestParallelClassOne">
        <test-method is-config="true" signature="setup()[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:19:57 CEST" name="setup" finished-at="2020-09-25T15:19:58 CEST" duration-ms="174" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:19:58 CEST" name="beforeMethod" finished-at="2020-09-25T15:20:03 CEST" duration-ms="5510" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test_1(java.lang.String)[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:20:03 CEST" name="test_1" data-provider="data-provider" finished-at="2020-09-25T15:20:11 CEST" duration-ms="7738" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Testautomatisierer]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at de.alain.TestNGParallel.TestParallelClassOne.test_1(TestParallelClassOne.java:168)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Starting test is test_1]]>
            </line>
            <line>
              <![CDATA[Test failed test_1]]>
            </line>
          </reporter-output>
        </test-method> <!-- test_1 -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:20:11 CEST" name="afterMethod" finished-at="2020-09-25T15:20:11 CEST" duration-ms="265" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_1 status=FAILURE method=TestParallelClassOne.test_1(java.lang.String)[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06] output=Starting test is test_1]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="beforeMethod()[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:20:11 CEST" name="beforeMethod" finished-at="2020-09-25T15:20:11 CEST" duration-ms="0" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- beforeMethod -->
        <test-method signature="test_1(java.lang.String)[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:20:11 CEST" name="test_1" data-provider="data-provider" finished-at="2020-09-25T15:20:11 CEST" duration-ms="30" status="FAIL">
          <params>
            <param index="0">
              <value>
                <![CDATA[Testanalyst]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [false] but found [true]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [false] but found [true]
at org.testng.Assert.fail(Assert.java:97)
at org.testng.Assert.failNotEquals(Assert.java:968)
at org.testng.Assert.assertFalse(Assert.java:65)
at org.testng.Assert.assertFalse(Assert.java:75)
at de.alain.TestNGParallel.TestParallelClassOne.test_1(TestParallelClassOne.java:168)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.base/java.lang.reflect.Method.invoke(Method.java:566)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:135)
at org.testng.internal.TestInvoker.invokeMethod(TestInvoker.java:598)
at org.testng.internal.TestInvoker.invokeTestMethod(TestInvoker.java:174)
at org.testng.internal.MethodRunner.runInSequence(MethodRunner.java:46)
at org.testng.internal.TestInvoker$MethodInvocationAgent.invoke(TestInvoker.java:821)
at org.testng.internal.TestInvoker.invokeTestMethods(TestInvoker.java:147)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:146)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:128)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1540)
at org.testng.TestRunner.privateRun(TestRunner.java:767)
at org.testng.TestRunner.run(TestRunner.java:588)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:384)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:378)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:337)
at org.testng.SuiteRunner.run(SuiteRunner.java:286)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:53)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:96)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1214)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1136)
at org.testng.TestNG.runSuites(TestNG.java:1066)
at org.testng.TestNG.run(TestNG.java:1034)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
            <line>
              <![CDATA[Starting test is test_1]]>
            </line>
            <line>
              <![CDATA[Test failed test_1]]>
            </line>
          </reporter-output>
        </test-method> <!-- test_1 -->
        <test-method is-config="true" signature="afterMethod(org.testng.ITestResult)[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:20:11 CEST" name="afterMethod" finished-at="2020-09-25T15:20:16 CEST" duration-ms="4278" status="PASS">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=test_1 status=FAILURE method=TestParallelClassOne.test_1(java.lang.String)[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06] output=Starting test is test_1]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterMethod -->
        <test-method is-config="true" signature="EndTest()[pri:0, instance:de.alain.TestNGParallel.TestParallelClassOne@957e06]" started-at="2020-09-25T15:20:16 CEST" name="EndTest" finished-at="2020-09-25T15:20:16 CEST" duration-ms="260" status="PASS">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- EndTest -->
      </class> <!-- de.alain.TestNGParallel.TestParallelClassOne -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
